config/routes.rb
::Refinery::Application.routes.draw do
  resources :products, :only => [:index, :show]
  resource :love, :only => [:create, :destroy]
  resource :worn, :only => [:create, :destroy]
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :products, :except => :show do
      collection do
        post :update_positions
      end
    end
    resources :brands, :only => [:new, :create ]
    resources :categories, :only => [:new, :create ]
    resource :category, :only => :destroy
  end
  
  resources :carts, :only => [:index, :create, :update]
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :carts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :cart_items, :only => [:destroy]
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  acts_as_indexed :fields => [:id]
  
  has_many :items, :class_name => "CartItem", :dependent => :destroy
  
  has_friendly_id :cart_name, :use_slug => true

  belongs_to :member
  
  def add_item(product, price, video)
    if item = self.items.where(:product_id => product).first
      item.quantity += 1
      item.save
    else
      self.items.create(:product_id => product, :price => price, :video_id => video)
    end
  end
  
  def cart_name
    if member.first_name.blank? & member.last_name.blank?
      member.email.split("@")[0]
    else
      member.first_name + ' ' + member.last_name
    end
  end
  
  def subtotal
    items.map(&:subtotal).reduce(:+)
  end
  
end

app/controllers/admin/carts_controller.rb
module Admin
  class CartsController < Admin::BaseController

    crudify :cart,
            :title_attribute => 'name', :xhr_paging => true

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_filter :find_current_member
  before_filter :find_shopping_cart!

  def index
  end
  
  def create
    product = Product.find(params[:product_id])
    video = Video.find(params[:video_id]) unless params[:video_id].nil?

    @shopping_cart.add_item(product.id, product.price, video.id)
    @shopping_cart.save

    redirect_to carts_path
  end
  
  def update
    cart = Cart.where(:member_id => @member_id).first
    item = cart.items.where(:id => params[:id]).first
    item.quantity = params[:cart_item][:quantity]
    item.save
    render :index
  end

protected

  def find_current_member
    if member_signed_in?
      @member_id = current_member.id
    else
      redirect_to new_member_session_path
    end
  end
end

app/views/admin/carts/_actions.html.erb
<ul>
  <% if Admin::CartsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_carts_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to t('.create_new'), new_admin_cart_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::CartsController.sortable? and Cart.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Carts"),
                 admin_carts_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Carts"),
                 admin_carts_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/carts/_cart.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(cart) -%>">
  <span class='title'>
    <%= cart.name %>
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), cart_path(cart),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_cart_path(cart),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_cart_path(cart),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => cart.name),
        :method => :delete %>
  </span>
</li>

app/views/admin/carts/_carts.html.erb
<%= will_paginate @carts %>
<%= render :partial => "sortable_list" %>

app/views/admin/carts/_form.html.erb
<%= form_for [:admin, @cart] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @cart,
          :include_object_name => true
        } %>
  
  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.carts.cart'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @cart.name)
              } %>
<% end -%>

app/views/admin/carts/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @carts.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'carts' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/carts/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'cart', :collection => @carts %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/carts/edit.html.erb
<%= render :partial => "form" %>

app/views/admin/carts/index.html.erb
<section id='records'>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::CartsController.sortable? and Cart.count > 1 %>

app/views/admin/carts/new.html.erb
<%= render :partial => "form" %>