config/routes.rb
::Refinery::Application.routes.draw do
  resources :products, :only => [:index, :show]
  resource :love, :only => [:create, :destroy]
  resource :worn, :only => [:create, :destroy]
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :products, :except => :show do
      collection do
        post :update_positions
      end
    end
    resources :brands, :only => [:new, :create ]
    resources :categories, :only => [:new, :create ]
    resource :category, :only => :destroy
  end
  
  resources :carts, :only => [:index, :create, :update]
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :carts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :cart_items, :only => [:destroy]
end

app/models/cart.rb
class Cart < ActiveRecord::Base

  acts_as_indexed :fields => [:id]
  
  has_many :items, :class_name => "CartItem", :dependent => :destroy
  
  has_friendly_id :cart_name, :use_slug => true

  belongs_to :member
  
  def add_item(product, price, video)
    if item = self.items.where(:product_id => product).first
      item.quantity += 1
      item.save
    else
      self.items.create(:product_id => product, :price => price, :video_id => video)
    end
  end
  
  def cart_name
    if member.first_name.blank? & member.last_name.blank?
      member.email.split("@")[0]
    else
      member.first_name + ' ' + member.last_name
    end
  end
  
  def subtotal
    items.map(&:subtotal).reduce(:+)
  end
  
end

app/controllers/admin/carts_controller.rb
module Admin
  class CartsController < Admin::BaseController

    crudify :cart,
            :title_attribute => 'name', :xhr_paging => true

  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  before_filter :find_current_member
  before_filter :find_shopping_cart!

  def index
  end
  
  def create
    product = Product.find(params[:product_id])
    video = Video.find(params[:video_id]) unless params[:video_id].nil?

    @shopping_cart.add_item(product.id, product.price, video.id)
    @shopping_cart.save

    redirect_to carts_path
  end
  
  def update
    cart = Cart.where(:member_id => @member_id).first
    item = cart.items.where(:id => params[:id]).first
    item.quantity = params[:cart_item][:quantity]
    item.save
    render :index
  end

protected

  def find_current_member
    if member_signed_in?
      @member_id = current_member.id
    else
      redirect_to new_member_session_path
    end
  end
end

app/views/carts/_cart_item.html.haml
%tr
  %td 
    = item.product.name
  %td
    = number_to_currency item.price
  %td
    = form_for item, :url => cart_path(item) do |f|
      = f.text_field :quantity
      = f.submit 'Update'
  %td
    = number_to_currency item.subtotal
  %td
    = link_to "Remove", cart_item_path(item.id), :method => :delete

app/views/carts/index.html.haml
%h2 Shopping Cart
- unless @shopping_cart.items.empty?
  %table
    = render :partial => 'cart_item', :collection => @shopping_cart.items, :as => :item
    %tr
      %td
      %td
      %td Subtotal
      %td 
        = number_to_currency @shopping_cart.subtotal
  = link_to 'Place Order', "#"
- else
  %h3 Your Shopping cart is empty!
  = link_to 'Continue shopping', products_path