config/routes.rb
::Refinery::Application.routes.draw do
  resources :products, :only => [:index, :show]
  resource :love, :only => [:create, :destroy]
  resource :worn, :only => [:create, :destroy]
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :products, :except => :show do
      collection do
        post :update_positions
      end
    end
    resources :brands, :only => [:new, :create ]
    resources :categories, :only => [:new, :create ]
    resource :category, :only => :destroy
  end
  
  resources :carts, :only => [:index, :create, :update]
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :carts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :cart_items, :only => [:destroy]
end

app/models/product.rb
class Product < ActiveRecord::Base

  acts_as_indexed :fields => [:name, :description]
  alias_attribute :title, :name

  has_friendly_id :name, :use_slug => true
  
  has_many :comments, :as => :comentable, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => true
  validates :description, :presence => true
  validates :price, :presence => true

  belongs_to :picture, :class_name => 'Image'
  belongs_to :brand
  belongs_to :category
  belongs_to :sub_category, :class_name => 'Category'
  
  has_many :love, :as => :loveable, :dependent => :destroy
  has_many :worns, :as => :wornable, :dependent => :destroy
  has_many :cart_items, :dependent => :destroy
  
  after_save :expire_cache
  before_destroy :ensure_not_referenced_by_any_cart_item

  delegate :name, :to => :slug, :prefix => true, :allow_nil => true

  def loved_by?(member)
    love.map(&:member_id).include? member.id if member
  end

  def worn_by?(member)
    worns.map(&:member_id).include? member.id if member
  end

  def self.by_brand(brand)
    brand_id = brand.to_i
    joins(:brand).where(:brands => {:id => brand_id})
  end

  def self.by_category(category)
      category_id = category.to_i
    joins(:category).where(:categories => {:id => category_id})
  end
  
  def ensure_not_referenced_by_any_cart_item
    if cart_items.count.zero?
      return true
    else
      errors[:base] << "Cart Items present"
      return false
    end
  end

private
  def expire_cache
    Rails.cache.delete("views/product_thumbnail/#{self.id}")
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::BaseController
    before_filter :find_all_brands
    before_filter :find_all_categories

    crudify :product,
            :title_attribute => 'name', :xhr_paging => true

    def index
      per_page = params[:per_page].present? ? params[:per_page].to_i : 20
      params[:page] ||= 1
      unless params[:q].blank?
        @products = Product.where('name like ?', "%#{params[:q]}%").select("name,id")
        render :json => @products.map! { |product| {"id" => product.id, "name" => product.name} }
      else
        unless params[:search].blank?
          query_products= {:name_or_description_or_category_name_or_sub_category_name_contains => params[:search]}
          products = Product.search(query_products)
          @products = products.relation.paginate(:page => params[:page], :per_page => per_page)
        else
          @products = Product
          @products = case params[:order]
            when 'loved'
              @products.order('loves_count DESC').paginate(:page => params[:page], :per_page => per_page)
            when 'commented'
              @products.order('comments_count DESC').paginate(:page => params[:page], :per_page => per_page)
            else
              @products.paginate(:page => params[:page], :per_page => per_page)
                      end
        end
        render :partial => 'products' if request.xhr?
      end
    end


    def find_all_brands
      @brands = Brand.all
      @brand = Brand.new
    end

    def find_all_categories
      @categories = Category.where(:parent_id => nil)
      @category = Category.new
    end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper :love
  helper :rank
  helper :worn
  helper :share
  include ProductsFilter
  include ResourcesFilter

  before_filter :find_page

  def index
    present(@page)

    products!

    if @not_found
      return error_404
    end
    @branch = params[:kind] ? params[:kind] : params[:resource]
    @leaf = params[:kind_name] ? params[:kind_name] : params[:filter_name]
    
  end

  def show
    @product = Product.find(params[:id])
    @related_videos = Video.by_product @product
    
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @product in the line below:
    present(@page)
  end
  
protected

  def find_page
    @page = Page.where(:link_url => "/products").first
  end
  
end

app/views/admin/products/_actions.html.erb
<ul>
  <% if Admin::ProductsController.searchable? %>
    <li>
      <%= render :partial => "/shared/admin/search",
                  :locals => {
                    :url => admin_products_path
                  } %>
    </li>
  <% end %>
  <li>
    <%= link_to "Most loved", admin_products_path(:order => 'loved')  %>
  </li>
  <li>
    <%= link_to "Most commented", admin_products_path(:order => 'commented')  %>
  </li>
  <li>
    <%= link_to t('.create_new'), new_admin_product_path,
                 :class => "add_icon" %>
  </li>
<% if !searching? and Admin::ProductsController.sortable? and Product.count > 1 %>
  <li>
    <%= link_to t('.reorder', :what => "Products"),
                 admin_products_path,
                 :id => "reorder_action",
                 :class => "reorder_icon" %>

    <%= link_to t('.reorder_done', :what => "Products"),
                 admin_products_path,
                 :id => "reorder_action_done",
                 :style => "display: none;",
                 :class => "reorder_icon" %>
  </li>
<% end %>
</ul>

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product] do |f| -%>
  <%= render :partial => "/shared/admin/error_messages", :locals => {
          :object => @product,
          :include_object_name => true
        } %>

  <div class='field'>
    <%= f.label :name -%>
    <%= f.text_field :name, :class => 'larger widest'  -%>
  </div>

  <div class='field one_row_field'>
    <%= f.label :brand -%>
    <%= collection_select('product', 'brand_id', @brands, :id, :name, :prompt => true) -%>
    <%= link_to 'Add brand', new_admin_brand_path(:dialog => true, :width => 300, 
                                                     :height => 250),
                                                     { :class => 'button', :id => 'add-category-link' } %>
  </div>

  <%= render :partial => 'admin/categories/categories', :locals => {:f => f, :resource => @product, :categories => @categories}%>
  
  <div class='field one_row_field'>
    <%= f.label :price -%>
    <%= f.text_field :price, :class=> 'price'  -%>
  </div>
  
  <div class='field'>
    <%= f.label :picture -%>
    <%= render :partial => "/shared/admin/image_picker", :locals => {
          :f => f,
          :field => :picture_id,
          :image => @product.picture,
          :toggle_image_display => false
        } %>

  <div class='field'>
    <div id='page-tabs' class='clearfix ui-tabs ui-widget ui-widget-content ui-corner-all'>
      <ul id='page_parts'>
        <% [:description].each_with_index do |part, part_index| %>
          <li class='ui-state-default<%= ' ui-state-active' if part_index == 0 %>'>
            <%= link_to part.to_s.titleize, "##{part}" %>
          </li>
        <% end %>
      </ul>

      <div id='page_part_editors'>
        <% [:description].each do |part| %>
          <div class='page_part' id='<%= part %>'>
            <%= f.text_area part, :rows => 20, :class => 'wymeditor widest' -%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  
  <%= render :partial => "/shared/admin/form_actions",
              :locals => {
                :f => f,
                :continue_editing => false,
                :delete_title => t('delete', :scope => 'admin.products.product'),
                :delete_confirmation => t('message', :scope => 'shared.admin.delete', :title => @product.name)
              } %>
<% end -%>

<% content_for :stylesheets do %>
  <%= stylesheet_link_tag 'custom' %>
<% end %>

<% content_for :javascripts do %>
<%= javascript_include_tag 'jquery.numeric' %>
  <script>
    $(document).ready(function(){
      page_options.init(false, '', '');
      $(".price").numeric({
        negative: false
      });
      $("#product_category_id").change(function(){
        var parent_category_id = "";
        var sub_category_options = "";
        $("select#product_category_id option:selected").each(function () {
          parent_category_id += $(this).val();
        });
        sub_category_options = $("#sub_categories_for_" + parent_category_id ).html();
        $("select#product_sub_category_id").empty();
        $("select#product_sub_category_id").append( sub_category_options );
      });
    });

  </script>

<% end %>

app/views/admin/products/_product.html.erb
<li class='clearfix record <%= cycle("on", "on-hover") %>' id="<%= dom_id(product) -%>">
  <span class='title'>
    <%= product.name %> <%= product.love.count %> loves <%= product.comments.count %> comments
    <span class="preview">&nbsp;</span>
  </span>
  <span class='actions'>
    <%= link_to refinery_icon_tag("application_go.png"), product_path(product),
        :title => t('.view_live_html'),
        :target => "_blank" %>
    <%= link_to refinery_icon_tag("application_edit.png"), edit_admin_product_path(product),
         :title => t('.edit') %>
    <%= link_to refinery_icon_tag("delete.png"), admin_product_path(product),
        :class => "cancel confirm-delete",
        :title => t('.delete'),
        :confirm => t('message', :scope => 'shared.admin.delete', :title => product.name),
        :method => :delete %>
  </span>
</li>

app/views/admin/products/_products.html.erb
<%= will_paginate @products %>
<%= render :partial => "sortable_list" %>

app/views/admin/products/_records.html.erb
<% if searching? %>
  <h2><%= t('results_for', :scope => 'shared.admin.search', :query => params[:search]) %></h2>
<% end %>
<% if @products.any? %>
  <div class='pagination_container'>
    <%= render :partial => 'products' %>
  </div>
<% else %>
  <p>
    <% unless searching? %>
      <strong>
        <%= t('.no_items_yet') %>
      </strong>
    <% else %>
      <%= t('no_results', :scope => 'shared.admin.search') %>
    <% end %>
  </p>
<% end %>

app/views/admin/products/_sortable_list.html.erb
<ul id='sortable_list'>
  <%= render :partial => 'product', :collection => @products %>
</ul>
<%= render :partial => "/shared/admin/sortable_list",
            :locals => {
              :continue_reordering => (local_assigns.keys.include?(:continue_reordering)) ? continue_reordering : true
            } %>

app/views/admin/products/index.html.erb
<section id='records'>
  <section id='records count'>
    <%= Product.count %> Products
  </section>
  <%= render :partial => 'records' %>
</section>
<aside id='actions'>
  <%= render :partial => 'actions' %>
</aside>
<%= render :partial => '/shared/admin/make_sortable',
            :locals => {
              :tree => false
            } if !searching? and Admin::ProductsController.sortable? and Product.count > 1 %>