config/routes.rb
::Refinery::Application.routes.draw do
  resources :products, :only => [:index, :show]
  resource :love, :only => [:create, :destroy]
  resource :worn, :only => [:create, :destroy]
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :products, :except => :show do
      collection do
        post :update_positions
      end
    end
    resources :brands, :only => [:new, :create ]
    resources :categories, :only => [:new, :create ]
    resource :category, :only => :destroy
  end
  
  resources :carts, :only => [:index, :create, :update]
  
  scope(:path => 'refinery', :as => 'admin', :module => 'admin') do
    resources :carts, :except => :show do
      collection do
        post :update_positions
      end
    end
  end
  resources :cart_items, :only => [:destroy]
end

app/models/product.rb
class Product < ActiveRecord::Base

  acts_as_indexed :fields => [:name, :description]
  alias_attribute :title, :name

  has_friendly_id :name, :use_slug => true
  
  has_many :comments, :as => :comentable, :dependent => :destroy

  validates :name, :presence => true, :uniqueness => true
  validates :description, :presence => true
  validates :price, :presence => true

  belongs_to :picture, :class_name => 'Image'
  belongs_to :brand
  belongs_to :category
  belongs_to :sub_category, :class_name => 'Category'
  
  has_many :love, :as => :loveable, :dependent => :destroy
  has_many :worns, :as => :wornable, :dependent => :destroy
  has_many :cart_items, :dependent => :destroy
  
  after_save :expire_cache
  before_destroy :ensure_not_referenced_by_any_cart_item

  delegate :name, :to => :slug, :prefix => true, :allow_nil => true

  def loved_by?(member)
    love.map(&:member_id).include? member.id if member
  end

  def worn_by?(member)
    worns.map(&:member_id).include? member.id if member
  end

  def self.by_brand(brand)
    brand_id = brand.to_i
    joins(:brand).where(:brands => {:id => brand_id})
  end

  def self.by_category(category)
      category_id = category.to_i
    joins(:category).where(:categories => {:id => category_id})
  end
  
  def ensure_not_referenced_by_any_cart_item
    if cart_items.count.zero?
      return true
    else
      errors[:base] << "Cart Items present"
      return false
    end
  end

private
  def expire_cache
    Rails.cache.delete("views/product_thumbnail/#{self.id}")
  end
end

app/controllers/admin/products_controller.rb
module Admin
  class ProductsController < Admin::BaseController
    before_filter :find_all_brands
    before_filter :find_all_categories

    crudify :product,
            :title_attribute => 'name', :xhr_paging => true

    def index
      per_page = params[:per_page].present? ? params[:per_page].to_i : 20
      params[:page] ||= 1
      unless params[:q].blank?
        @products = Product.where('name like ?', "%#{params[:q]}%").select("name,id")
        render :json => @products.map! { |product| {"id" => product.id, "name" => product.name} }
      else
        unless params[:search].blank?
          query_products= {:name_or_description_or_category_name_or_sub_category_name_contains => params[:search]}
          products = Product.search(query_products)
          @products = products.relation.paginate(:page => params[:page], :per_page => per_page)
        else
          @products = Product
          @products = case params[:order]
            when 'loved'
              @products.order('loves_count DESC').paginate(:page => params[:page], :per_page => per_page)
            when 'commented'
              @products.order('comments_count DESC').paginate(:page => params[:page], :per_page => per_page)
            else
              @products.paginate(:page => params[:page], :per_page => per_page)
                      end
        end
        render :partial => 'products' if request.xhr?
      end
    end


    def find_all_brands
      @brands = Brand.all
      @brand = Brand.new
    end

    def find_all_categories
      @categories = Category.where(:parent_id => nil)
      @category = Category.new
    end

  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  helper :love
  helper :rank
  helper :worn
  helper :share
  include ProductsFilter
  include ResourcesFilter

  before_filter :find_page

  def index
    present(@page)

    products!

    if @not_found
      return error_404
    end
    @branch = params[:kind] ? params[:kind] : params[:resource]
    @leaf = params[:kind_name] ? params[:kind_name] : params[:filter_name]
    
  end

  def show
    @product = Product.find(params[:id])
    @related_videos = Video.by_product @product
    
    # you can use meta fields from your model instead (e.g. browser_title)
    # by swapping @page for @product in the line below:
    present(@page)
  end
  
protected

  def find_page
    @page = Page.where(:link_url => "/products").first
  end
  
end

app/views/products/_product.html.haml
.item.product
  = link_to product_path(product) do
    %span.image
      - if product.picture
        = image_tag product.picture.thumbnail('150x130#').url, :alt => product.name
      - else
        = image_tag 'small-product.jpg'
    %span.name
      = product.name.size > 15 ? "#{product.name.slice(0..15)}..." : product.name
    %span.info
      = number_to_currency product.price

app/views/products/_rank.html.haml
.rankMenu.push-1.span-17.last
  %ul.sortMenu
    %li
      sort by:
    %li
      = link_to "most loved", most_loved, (@order_by == 'loved')? {:class => 'selected'} : {}
    %li
      = link_to "lowest price", lowest_price, (@order_by == 'lowest-price')? {:class => 'selected'} : {} 
    %li
      = link_to "highest price", highest_price, (@order_by == 'highest-price')? {:class => 'selected'} : {}

app/views/products/index.html.haml
%aside.leftMenu.span-6.first
  %h4 Products
  %ul
    = dinamic_filters @dynamic_menus
    = manual_filters

    - if @filter_options[:brand]
      = new_products_brand_menu

%section#product_list.itemsList.span-18.last
  .rankMenu.push-1.span-17.last
    %ul.sortMenu
      %li
        sort by:
      %li
        = link_to "most loved", most_loved
      %li
        = link_to "lowest price", lowest_price 
      %li
        = link_to "highest price", highest_price
    = paginator @products
  #products.items
    = render @products if @products
  .bottomPage.push-1.span-17.last
    = paginator @products

app/views/products/show.html.haml
%section#product.span-17.last
  %span.breadcrumb
    MAKEUP : #{@product.category.name if @product.category} : #{@product.name}
  #product_image.span-8.image
    - if @product.picture
      = image_tag @product.picture.thumbnail('260x260#').url
    - else
      = image_tag 'large-product.jpg'
  #product_info
    %h2= @product.name
    %h3.brand= @product.brand.name
    = raw @product.description
  #product_menu.prepend-8
    %ul
      %li
        = love_button(@product)
      %li 
        = link_to 'Add to cart', carts_path(:product_id => @product.id), :method => :post
      %li
        = share_button(@product)
%section.span-23.last.relatedContent
  %h3 Looks with this product
  .span-23.last
    = render :partial => 'shared/related_videos', :locals => { :related_videos => @related_videos }
%section.span-23.last.relatedContent
  %h3 Tell us why you love this product
  .commentBox
    = comment_list(@product)
    = comment_form(@product)

= javascript_include_tag 'http://platform.twitter.com/widgets.js'
= javascript_include_tag 'http://static.ak.fbcdn.net/connect.php/js/FB.Share'